version: '3.9'

services:
  app:
    build: .
    command: "python manage.py migrate && gunicorn A.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/lol/
    networks:
      - main
    ports:
      - "8000:8000"
    restart: always
  nginx:
    container_name: nginx
    depends_on:
      - app
    command: nginx -g 'daemon off;'
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  main: